# Setup
title:        ModernFuzzBall2
tagline:      Projects
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Markus
  url:        https://modernfuzzball2.github.io
  email:      modernfuzzball2@opticalraze.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
